### ISSUE TITLE
[Kaggle Notebooks] Create Kaggle Notebooks for course units

### ISSUE THREAD

**Issue by Vaibhavs10** [huggingface/audio-transformers-course#111]
Hi there :wave:

Many course participants faced issues working through the course materials and exercises on a free tier of Google Colab. An alternative to it is Kaggle Notebooks (it provides a fixed amount of GPU hours but is consistent in experience).
However, there are some differences in working with Kaggle notebooks, such as pushing models to Hub and setting up your environment.

How can you help?

- Write a short tutorial illustrating the extra steps needed to run the course examples and exercises successfully in Kaggle Notebooks.
- Once done, tag [@MKhalusova](https://github.com/MKhalusova) and [@Vaibhavs10](https://github.com/Vaibhavs10) in the comments. We can review and suggest changes if required.

Thank you for deciding to volunteer your time and experience with the course.

**Comment by michaelshekasta** [comment]
I have created a notebook that should help to run in Kaggle: https://tinyurl.com/ym7jp4b5

Pay attention: You can't push your model with push_to_hub (git issues), you should upload a folder as a pr (workaround)

If you have any question, feel free to reach me

**Comment by crowbarmassage** [comment]
I'm getting this error in Unit 4 and Unit 5.  I did do both pip installs as the error message suggested.

ImportError: Using the Trainer with PyTorch requires accelerate>=0.20.1: Please run pip install transformers[torch] or pip install accelerate -U

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by michaelshekasta** [comment]
@crowbarmassage Can you share you notebook code?

**Comment by MKhalusova** [comment]
@michaelshekasta Thank you for creating a Kaggle notebook with an example. I'll add a note to the Get Ready | Set up section of Unit 0 mentioning your work.

**Comment by Vaibhavs10** [comment]
Closing this issue since this has been merged in #133
